name: bump_rpicamera

on:
  schedule:
  - cron: '4 5 * * *'
  workflow_dispatch:

jobs:
  bump_rpicamera:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - run: >
        git config user.name mediamtx-bot
        && git config user.email bot@mediamtx
        && ((git checkout deps/mediamtx-rpicamera && git rebase ${GITHUB_REF_NAME}) || git checkout -b deps/mediamtx-rpicamera)

    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const fs = require('fs').promises;

          // get last release
          let curRelease = null;
          for (let i = 1; i < 20; i++) {
            const releases = await github.rest.repos.listReleases({
              owner: 'bluenviron',
              repo: 'mediamtx-rpicamera',
              page: i,
            });
            for (const release of releases.data) {
              curRelease = release;
              break;
            }
            if (curRelease !== null) {
              break;
            }
          }

          // write version to disk
          await fs.writeFile('internal/staticsources/rpicamera/mtxrpicamdownloader/VERSION', curRelease['tag_name'] + '\n', 'utf-8');

          // make version available to next steps
          core.exportVariable('VERSION', curRelease.name);

    - id: check_repo
      run: >
        test -n "$(git status --porcelain)" && echo "update=1" >> "$GITHUB_OUTPUT" || echo "update=0" >> "$GITHUB_OUTPUT"

    - if: ${{ steps.check_repo.outputs.update == '1' }}
      run: >
        git reset ${GITHUB_REF_NAME}
        && git add .
        && git commit -m "bump mediamtx-rpicamera to ${VERSION}"
        && git push --set-upstream origin deps/mediamtx-rpicamera --force

    - if: ${{ steps.check_repo.outputs.update == '1' }}
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const prs = await github.rest.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
            head: `${context.repo.owner}:deps/mediamtx-rpicamera`,
            state: 'open',
          });

          if (prs.data.length == 0) {
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'deps/mediamtx-rpicamera',
              base: context.ref.slice('refs/heads/'.length),
              title: `bump mediamtx-rpicamera to ${process.env.VERSION}`,
            });
          } else {
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prs.data[0].number,
              title: `bump mediamtx-rpicamera to ${process.env.VERSION}`,
            });
          }
